version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - .:/react_frontend
    container_name: react_frontend-c
    image: react_frontend-img
    ports:
      - 3000:3000
    command: npm start
    environment:
      - WACTHPACK_POLLING=true
