version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - .:/ecommerce_django_api
    container_name: ecommerce_django_api-c
    image: ecommerce_django_api-img
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - WACTHPACK_POLLING=true
    depends_on:
      - db
  db:
    image: postgres
    container_name: nga-postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
        - 5432:5432
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # env_file: .env
